version: "3"

services:
  nuget.example.org:
    image: containinger/nugetcachingproxy:latest
    container_name: nuget.example.org
    volumes:
      - ./data/logs:/app/logs
    restart: unless-stopped
    networks:
      - web
    environment:
      - TZ=Europe/Vienna
    labels:
      - traefik.enable=true
      - traefik.http.routers.nuget-cache.rule=Host(`nuget.example.org`)
      - traefik.http.routers.nuget-cache.entrypoints=web-secure
      - traefik.http.routers.nuget-cache.tls=true
      - traefik.http.routers.nuget-cache.tls.certresolver=le
      - traefik.http.services.nuget-cache.loadbalancer.server.port=80
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  web:
    external: true
